#!/usr/bin/env php
# life
<?php

require_once('vendor/autoload.php');
require_once('LifeCommand.php');

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new LifeCommand());
$application->run();
